{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-key-secret",
    "namespace": "letsencrypt-staging",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-key-secret",
        "namespace": "letsencrypt-staging",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "api-key": "AgDDCZvkcu8qlGPBwbd5flc36PShDxCuWtNKmh6bYTFQNMKWpY8vIxaeNF2hpg1Ik02MmObSVgJq84jSoiQ8mGFl+5ErByVAAhhjJzxrUzTMX1xLmJx237mqnGj/bu5XS90XU89024u1QxuYUmpqVKvUeBrWxFaAB+2lihjkBTLUbV4SADo95hU0ZBD+bu90gAJuoEn+lXHInufjYxbr42SZYQYGjHs86xIYDR/fRQcFyW9TUDSV1ynTiOBXw+3+ZnCcT21HEve8Y/MyFk83p/A91uMZoRMGTF5l40DLgyurQ9NMCnCB7WURqOAqUVEfI23rlzFoEY5sbAKl2JaHok0rMQQ9islBx0/ulKHkIea2CXpQMPU/icbDuagtU2KLiFfd58v0Z3siA5ykn4yXtMpGCym/Izg2V8+RJVG1SdI1GPIlUJC/eMmFEe6balaH29Q0qQJGhjsDw6FeD+6QPs6TAkgQizt9clEQ+dB3/kQeajoLvTKAnl9v5gxOpxVX7nuyya3an7lI+heBc2/czv2T0LLg1RLIHgKWwUPzzCEq1L/O5MSUENS51qrKqABq54pvKBioS4QtMk7KLnMt/la/l2pRdajPGhYqiMPseo6QxMwiAwYY9BozsdmLpp1gYouoHW3j9QEmjVeB+l4Jwn5QDK7r+7Y72BPFtGbkcPh3iBdnVzbGDLggMXUKfsHvWUnEPImux9iKG91JcAKpIfR+A3mGwEJA28shg3AjYHGZeLTUYM/V"
    }
  }
}
