{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-key-secrets",
    "namespace": "letsencrypt-staging",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-key-secrets",
        "namespace": "letsencrypt-staging",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "api-key": "AgDS9GSDQ18/TAmK1Nafy91/gv4+A87qSkXMgxP4sK36zviLUnOGN2Q7vrNutimXhmitMxuFWqD0SDU2AcLujE2zOVd5784TQ+ZaXIZ9AVn4w2MluRMxIFAt+kPOdevlN1Jd3jhiK/t4USfgBI/0SceD8m+nmJqM89wToTq7yeR2qPYMnjJs7BLetfldiJatwhd55PgEc6Y8UzgMc3TF+WCO0ZolGbwi/eATRxiu1ox6J1nmvaePZSvy/orZUq0bj8ZH4U8WEew4eFTfym/0DHCKbH1PNnxzVhuklQptYvOQccjhQ8JDDjSjMChO9NPsuRlWkXQwCVRPDCEm23AvQNRu4G0Ciwfpbyo4hlLJImPcsc3q4qRV7dcbLvTJHBLGfkncQCrANgJAr+T/Sysm8mb1SnBycGCYXIgVy6j8v7DHaJIsaneOW+7hqmuUXMyGVjuV+Dm3eVcgqxl85rVApR9y0dVGoABc9cPH8UP734iBgmW+2sPDkxPgPGhke2B03lq0FV4R2hECduqMzuJtogHtnZ9ivciBTedM4QFhst/PJhz3jCQdhmmCAOwCUt7cNCa5ER66Phvww9P8hOaUSzV15jM4r/DtT9o0QlmxUFjsk620f9ciavTa9XrQLEfu2WV6ytnPlwL2vuSZlot2y90LxUBKMNVs82CQuaeKoZIAkiX/i9htbpqDJybY0xMcnBaqF3AKtFazDiAY2+9As1DajsZn+EJfAv21zsathrObDNu0C7aJ"
    }
  }
}
