{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-key-secrets",
    "namespace": "letsencrypt-staging",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-key-secrets",
        "namespace": "letsencrypt-staging",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "api-key": "AgA1u8IfOEkxneK7ROiYkcnnfS1XvcIQi8n/89wdIOrQrYXFkUE/saB70mDBL24OMs/oohVx4XNEzgmNfrhAA4w0RHmXeh0sYeYwS7VrVxK4/XmZr4hxiLmybWtIaOt598FTAZOl63FT7uH7GlZbcoYn3IwjwFiJlsrTGgimX9p7xH8+ayJjewdjIogQyjR0rKtwNOa38zaY0sQprwt91kzF/eJUEBJ5/EGu7/II5hiAGfp40EO0SqoYKlhqFtJl66yRB8z6ehBx73CyNPMsnTCy+9Lju4IouAsgDWiVVr/3Mm4/28WfB79kg53k9vn0QvfOZ1AS2EtXOgYSrtzzamx6qtf8gB6sw7fmnoBLswbBrNwp4lO/p9ZAlOUZL9Vl/xV+d1i6maj8vPAYuePZ66pnOCZdsfE2FbLy/EHb2h3lSWY2zbfigJ5s5iQuxnJx8DUgOSz5AWVRKK3PKZST1+0DT9qF+ei5pfTtvj+khh90mYeRKc4zGEUzAjO7eit0ClKVzHCmNl67hP2PE6sVkVBbrOPmYQ8iXYWWC4P82qu+shUhyaMsxXsO9U5BDbWFWCijcI9xVoezXJla87vhLRrEnC9EioZdfrmoc/t4UzkyAExcjQ7B49uKDF/5jG/MGFq/9pED9upNH7i7sWpktOTzk7TQj5IKLRASfLjtDj3yboj2mdyG6LFEmDL0vV6NTkBZLAYuKnsXl8BMSKoN36jgMWEcA2rSp/auLYPq3X2bQ9gERc/f"
    }
  }
}
