---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer-letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: mattia.vallortigara@protonmail.com
    privateKeySecretRef:
      name: issuer-letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: mattia.vallortigara@protonmail.com
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "greyroom.net"