{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "gotify-secrets",
    "namespace": "gotify",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "gotify-secrets",
        "namespace": "gotify",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "GOTIFY_DEFAULTUSER_PASS": "AgDVphyuJXwAWbQ8qKN42vLejLRO3+8DRc9OPvM80a4OJ4dMLylHnQscPc4c1JQkHHgMlaFMvrhGqREOm0xVPct+ITKsgnZQo9MqGvEVxIPWDCtMt/RFMkY1YrbfNaTa8+3Q7xLxGiVRMcp7xAgkr0YL7BW/lEPbdvnBvwwh4ELZAbIJIMZAh0vDjEq4/+7VWTzM2Q3orQLoBsa0DNmin5GKDOfrmWRbHUIIDYEqtflMWFcky8qKiIy2eH14V68pnJi3+YHvAIecU993V0rxOSfdiVCCwqg28H1JZmEPXwPC0de7CEL09MoC4Ryz9z77IOzzjvty+7M9FrycL31qMu496FZHTob7tgqpQpu32y1TLKwnZRmNg5QtPgBHx/Vmj3UGIuH7FSL1hIxXy+SrDLhroZ5hQ50y4SYRoMBYongSo2ynS7axWb2NJ2MczFZ0tTLR5yW0+P/OGLQRSz2SU4uCFldb1DLREGN2iWtkCL++fnclNAUrZq2THgWLhU8SkC1WFfzlUKy7gzeryT3F32EXWn5RWorm57dbaQn2gYv5ZbeLkcXT5AR+8TXdH/TgO5uhaTNiTuq3dF/eTTud8WXo6ZBm/U3MpXWIDkcQHQzQ+uOhALAknDlP2wyL242R11RDTdSvs8DWqYGqb/rECQak0q21bhwDpxCMiommugq7uqDXi4kC3JtB7Gg9kL9yIQXdX0uCcrB/4BzgDCXd/w=="
    }
  }
}
