{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "paperless-ngx-secrets",
    "namespace": "paperless-ngx",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "paperless-ngx-secrets",
        "namespace": "paperless-ngx",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "PAPERLESS_ADMIN_PASSWORD": "AgDiCAZm2bHuXQeIVVGHlarmjwKKat9YRvlD597ut3AAZQYWe1VoNJ4MBf5WVwsWqgT7fA79ztsBEtYXZd933dx6SY8IFMVBt63CU1gH3TyFtfcs9KGaLlK3w2t8Ymz5UseA0yGozlyrT/nI4scUaB/gzwN6pNTugm91fpDKUAbitZjv06WXAhWPIwg2qAjb8AnJTqykkv9DvYbu+wM/Y5+1iUFuzP6OUeC1zIl/engfAVPNMmIZY3F7xI3zbgHt8dk1ZVURBs/K5MCZAieVi5dEy38y+Z8XQ97HB3NzzFubkdX/HnAtzeEmeYcqR/F4DE+eNCZiRdPVeG32Z6F8Vge7OtFWuNRYyToegCkLkGRQo5Hq9NdUEztQlW0nium5X6dvlDgrO+OYw4e+Ub7lndSiXd153aKX0K9VnTNq6xI8atb4nm94QMWn93TEQLavsACLES6SRRGT9xA9LVVPgIGd+K7gtMBk0lO4n5JsU9alXcuZ5fYasfVhF3M89UBGtQ7bgWsafVIs24SD/JJfsIz2gFCO7OgobUYLabhWffNZPZY9/yFKGwz07IQvx53yY5d7WzPbAdd07UJ6s1xTfSabqekjl3bpRKM7UYBOb4g/PbkDJg9OxyUmiY7HQjJOd3diGUuPss432HQkj34zN3lV491cR/C9p7SoTBvADUPOPnYMU+3M0+D6tMJ6lx+Mkyynt1mbdlKBpAZc2lSU7j112g==",
      "PAPERLESS_ADMIN_USER": "AgBuyJMh9q60FiUtSlhGZnUj9rV2wWEmP0IFBzm95d4o+h1F3pPfePS+7qFnKJYaiPZ/LhPzzO4FmBiG/ihE8B9sIymSvvY8mObwSpRkH2AjbTyOpbK++5TH4XvHLsnYQC6PfXBZfLjL+xw196wmDEcE3gL8qVt+NvSfqnIVgU/Ok94DMfWxHQYu8AbRCNdkgkGwPD9/q5EOnoyuVRHYXtZA6yzmSc5h2JbobwurdjPtEvPTMZQDrJAxE55vltAjgE/aJpp8tl14awk/TFpEWEtYgZhxCbkTOrD5rnWysxtJNpaF75gZQoWBv8wK0C6RES00tb/3LWyAo8vpDVad/Q1Fz20GWkO9K+UltzCDrDxTNWGCAC6ZzScH5bHUzTRD0lLiXeP3D0T2tAkx2ZpcaSU8I1vVFXahVq5JOi4ZIcaoIuEj4zM4dPE7+SBIHGKhCTvZik57QHQvTAU+i2NgC8yo024RvuOCDVEhnCmzBXZ53HZZCRP/UirpusbRs+sIIfljYfB3Gn9XK4oHb0oAdc+SLy75rVWBg184W1OYDMV3OonA6PAa97Pdrw20GZCUalVoWRWACE6Hu1kM96fCmgNh61gf2JRd05clQIEEiXnKh+dYMhc6uCdUGnVndCB5/hK4MabVmTCms3AxgOo3RkDD3Upsge6s+/h7NquW5Ej5OvLHj47Ee/366Rx030dL3hOg8aHm6no="
    }
  }
}
