{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "paperless-cnpg-db-app-password",
    "namespace": "paperless-ngx",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "paperless-cnpg-db-app-password",
        "namespace": "paperless-ngx",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "password": "AgBZHsbzwYi6zrPhQIXHrvdu4lQuzv4Q4cpOOmndsm/L+Vq7gUfnZbSQ/Kw/WCn6BI7/waXl4b0TFDqj7lHsHUdnt4Jh662R/4qnVoe1Mr/FXw0GcO0UEColyB6rcbwCl8dUPs6slAPNdd6bQPAe8zp58m3VWb4YLO2hO0AIhLpTlSvX29mw5ZFik/VknTD3gzB+EK+h2xoJznVX1ldwYQp2K7zjYl3sRz/9/EEi0rmmwGNxAmGhxp7gPcHX+B4xsj1LEHn5wiXDgD956W72Ev8TsL/ktXW3YhYCW+QodsJnZT824NP34Jkz31cBU547wqytVFneT5cIgoR4NwdpYvp0Q4zLDIAOLu2TSttn86DaMAu6AQSLQb/4ApB7sIJjiICXhCL+8Z1brH/qLHcGy3ioq3P99ONeDUHDZ9TDdeyEW/H89DQ2lcK3kMOBEOSofikaw/rBwPJZ+EFMtiNs4MF76DrAp9d5dOZZEejPeUOkTn5BUnpk46LAnPkaAvQ+jzFt+3wQXF/avt58jgfUWJwm+6LoWgjWhZ2IbSxX3V7GY/bkqmSvuqdKYhM4fgIVYBxcN+1i9B/cLCUBWw4FoGOvUKS1LOSu1Ji5UBngJXV1LqCLXxQ4QdceEKxMiCVfajNOrD87opv+gJYujzT9E/ceSmF67k4pr04AVRWtHRGhgtIw7ruAd6vNRRAKS9FqEliHKv46nj5a788aQR5Dj17SO+AuVg==",
      "username": "AgAp7ThQzbrW7CY8L39k2UQGJ1l6sKT/RGbpUSTFyupKPbU/ScZL6jGg1RzoxkVWzsLGXOXJU/BQxoYdQk44HYQwjDS5tP7nTbaptcutJbswC9zRZC3vra8Q53OwbpSwwQQWCXunIaze2AB+y2KphBKDEGJhjmtQZIyDlzhYKDz52BwhUW87tU7wpkE+eAutegKgYmv39e/3mAupQsmg6XEpXV1jPlBQjuSjjvk123oUoagbQQ1HeZJAS8bvPlZdx8vhfNgHuykgUinD9agnVUmRXuySnjZ7IO/PPECiYGhFGrRtzQxdUEPVyQwIlC0CZ57AdMu0f9tbRrUl+PXAUnXvIzP1hTgapRwFd0YW0PWPqUPpWGahEHhPyakCvnffv2hoYMjRmXHBLonzxRSB60hey9AUk3kGCEpILecSzv0uBQYBmKRfloyVaMtW1gLWEwzFIu1Oj6OGpDUn7ipKvvXSOm1uamTNASvCgZLtLCAx0U8Iy0v8bXGJbTfdXXN29Vg6p95WJzCcYYYWku9K3tUdtuQBFVm9ZtWIbT+ClHGFcwSorLb6gjhElPwm7CpZJJZ7gZnZ1y3cPUdhPwW9ZuYizOuMQ1+Q0LYus5EB7k/eNT5uDItMJSA3h9Pd3K3kjPJYo0+4WczvIky0Vy3nGIawri6RVuCubVDOgKdistMnS0n/jlOa4BKZmXqL0yvZLXXHAeQ="
    }
  }
}
