apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps-definitions
spec:
  sourceRepos: []
  sourceNamespaces: []
  destinations: []
  namespaceResourceBlacklist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-definitions
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/Gu35t09/TalosCluster.git
      revision: HEAD
      directories:
      - path: argocd/apps-definitions/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "apps-definitions"
      source:
        repoURL: https://github.com/Gu35t09/TalosCluster.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
          - CreateNamespace=true