apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  proxmox.yaml: |
    url: https://pve.greyroom.net:8006
    token: {{HOMEPAGE_VAR_PROXMOX_API_TOKEN}}
    secret: {{HOMEPAGE_VAR_PROXMOX_API_SECRET}}
  kubernetes.yaml: ""
  settings.yaml: |
    title: My Awesome Homepage 
    theme: dark # <----- add this line
    color: slate # <----- add this line
    background:
      image: https://images.unsplash.com/photo-1722342618130-6bb50c18550a?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
      blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 50 # 0-100

    providers:
      openwe  athermap: openweathermapapikey
      weatherapi: weathe

    useEqualHeights: true

    layout:
      Hypervisor:
        header: true
        style: row
        columns: 1
      Backup:
      GitOps Tools:
      Kubernetes:
      Networking:
      Services:
        header: true
        style: row
        columns: 4

  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
        - Stack Overflow:
            - abbr: SO
              href: https://stackoverflow.com/

    - Social:
        - Linkedin:
            - abbr: LK
              href: https://it.linkedin.com/
        - Reddit:
            - abbr: RD
              href: https://www.reddit.com/

    - Entertainment:
        - Anime World:
            - abbr: AW
              href: https://www.animeworld.so/
        - YouTube:
            - abbr: YT
              href: https://youtube.com/

  services.yaml: |
    - Hypervisor:
        - Tartarus:
            icon: proxmox.png
            href: https://pve.greyroom.net:8006
            description: Proxmox VE
            widget:
                type: proxmox
                url: https://pve.greyroom.net:8006
                username: {{HOMEPAGE_VAR_PROXMOX_API_TOKEN}}
                password: {{HOMEPAGE_VAR_PROXMOX_API_SECRET}}
    - Backup:
        - NAS QNAP TS-212:
            icon: qnap.png
            href: https://nas.greyroom.net
        - PBS:
            icon: proxmox-light.png
            href: https://pve.greyroom.net:8007
            description: Proxmox Backup Server
            widget:
                type: proxmoxbackupserver
                url: https://pve.greyroom.net:8007
                username: xx
                password: xx
    - Databases:
        - pgAdmin:
            icon: pgadmin.png
            href: https://pgadmin.greyroom.net/
            description: PostgreSQL Tools
    - Kubernetes:
        - ArgoCD:
            icon: argo-cd.png
            href: https://argocd.greyroom.net
            description: Declerative GitOps CD for Kubernetes
            widget:
                type: argocd
                url: https://argocd.greyroom.net
                key: "{{HOMEPAGE_VAR_ARGOCD_API_KEY}}"
        - Longhorn:
            icon: longhorn.png
            href: https://longhorn.greyroom.net
            description: Cloud native distributed block storage
    - Networking:
        - AP:
            icon: raspberrypi.png
            href: https://192.168.100.3
            description: Raspberry Pi Access Point
        - Mikrotik CRS310-8G+2S+IN:
            icon: mikrotik.png
            description: Switch Mikrotik
        - OpenSense Firewall:
            icon: opnsense.png
            href: http://opnsense.greyroom.net
            description: NGFW
    - Services: 
        - Immich:
            icon: immich.png
            href: https://immich.greyroom.net
            description: Photo and video backup 
            widget:
                type: immich
                url: https://immich.greyroom.net
                version: 2
                key: "{{HOMEPAGE_VAR_IMMICH_API_KEY}}"
        - Nextcloud:
            icon: nextcloud.png
            href: https://nextcloud.greyroom.net
            description: Cloud file storage and collaboration software
            widget:
                type: nextcloud
                url: https://nextcloud.greyroom.net
                username: mattia
                password: "{{HOMEPAGE_VAR_NEXTCLOUD_PASSWD}}"
        - Nginx Proxy Manager:
            icon: nginx-proxy-manager.png
            href: https://nginx.greyroom.net
            description: Reverse proxy for all services on docker
            widget:
                type: npm
                url: https://nginx.greyroom.net
                username: "{{HOMEPAGE_VAR_NPM_USER}}"
                password: "{{HOMEPAGE_VAR_NPM_PASSWD}}"
        - Paperless-ngx:
            icon: paperless-ngx.png
            href: https://paperless.greyroom.net
            description: Open-source document management system
        - PiHole:
            icon: pi-hole.svg
            href: https://pihole.greyroom.net/admin
            description: DNS server and AD blocker
            widget:
                type: pihole
                url: https://pihole.greyroom.net
                key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}"
        - Portainer:
            icon: portainer.png
            href: https://portainer.greyroom.net
            description: Container management software
            widget:
                type: portainer
                url: https://portainer.greyroom.net
                env: 2
                key: "{{HOMEPAGE_VAR_PORTAINER_API_TOKEN}}"
        - Vaultwarden:
            icon: vaultwarden.png
            href: https://vaultwarden.greyroom.net
            description: Password manager
        - Vikunja:
            icon: vikunja.png
            href: https://vikunja.greyroom.net/
            description: Open-source to-do app 
        - What's up Docker:
            icon: whats-up-docker.png
            href: https://wud.greyroom.net
            description: Notification system for docker update
            widget:
                type: whatsupdocker
                url: https://wud.greyroom.net



  widgets.yaml: |
    - datetime:
        text_size: xl
        format:
          timeStyle: short
    - search:
        provider: duckduckgo
        target: _blank

  docker.yaml: ""
