{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "gotify-api-key",
    "namespace": "homepage",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "gotify-api-key",
        "namespace": "homepage",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "key": "AgAt8bdApEuxJ9Q0slypcfK5n7UrqipQR6nqthtBzEAEPVNPKKGNGcba5TOZ2pvVCHAMukqQLb2dW9iUAtsxeznKBV5tMAwXEltR6EIL15MUPbg6UG/DzlUuzoHjj44N3WXtBPVGMyNxjOl4XPRW8XWI+yxcNGUYstaTIczKfdkoHi8JsYkyVXr574dZZ8DHFnpBSBtUp7TiKKofS5wAEMZtAF5b+1FIP8eJlTDcUceFW7u+gqyIfEk5i2wfqcUfW1l/UOQECaXwh66PvJQ1N1Guz6BOu8IVSTT3HUOebnPGdr0UELSyeMZKHKO7ls5A/afx9aftpFxt5mN7EmbHFiS8twETcp8YGBLHgWNWU+NLGOUKMuHOYKF0Xzlvg1nZc0rHk2JdSBvRDa13rukMTA1XGUrv9VIRrMtujSfKSKewQoBB4KG5s0+JlaO8Z8e1QPWbOF0G8ynKxiNip1Ps3SSb8mR4KQdE/rARpdpCVzEpnAsIh1nRYV4wyahOZ5+JHXg5aCMGrAksZH81PFDVtpDCvRPk9nAGuwM3IlAB8Z8CCo+jkrt323Z2NZ+/+0/g6vAWAhiKWZw5wLfN+eeu02JP7e/artdVShlonmzeHunQ/xQu4fuQB334TFffd5PTBd0CBZzThDSaipEiWjKjwYk7fBQTiWd1IPdxGLxOkANuXxAw1pR5kboF2SDM2+4+RmuZNOHRkQwn7wRDMFg2Ayk="
    }
  }
}
