{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "nextcloud-passwd",
    "namespace": "homepage",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "nextcloud-passwd",
        "namespace": "homepage",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "password": "AgATYC6NTHi09T9tJfuU674zck9QxOA0dovVyjItupEnhp4heyGPpBVQUE3So2r/TSz+mFwoDez46n78wGfW0gMyEacAMSYwrJVcm0YOAbvH+S+EyOSOmMrECRr4Vyrwwb56koF9qbN6q4azhGPsPobYFDq1QEqjoHqQgQJyONwomSemhR24a0Uxi+rEUdi9/X3Fh70ckCMA+oCgZjIEfHT3+HL7hMn3QkcnKNAPtBo6jyM1XlNgfjAZ4ArXEhTIBjHElkMaCCSuu5EFKcwg33QA8j5cLi7pIjK4Vqpy8VF/NKudrRaDgLcc0Ay2N89Ivswx5GVqYL67m6wr2m1bNpu0HY6dFshsk/6Tu4+kxo7/sCRwUbdwtFrpqzoEgEbZpbQuVELrzfANO8xDp95riJInc1yAHLkR63q3S+/P7FHHk9ueDluumkVdST5oeGoKKK0oDFXUAU4JybNsP7HTzu7D2LcUA03zDznMWyE+Xoxn+J0LPRG24kSQDJxj+e8Ai5yrCJuRB/4/ycCAH+KjoTRUGuS/xNRhLHUNIRhXQTqsrjjm7R87ceWqOF3Ly380TwPeubDxE3C6Kh2TkFqAVcIj8H3tWH93eFVb68MMl+AdEMO4nqyMPiWDWxUEb2DBgKaXViT7D4JHpKFrT4ntDc0+v1f6DEh6w7etTLYGML5XGEe/PJxmQhlDd3/jYZuuQEnSGwGK6jKzuzuxyl3lUa06mJdA0exz4nb2btwJMw=="
    }
  }
}
