{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "npm-credentials",
    "namespace": "homepage",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "npm-credentials",
        "namespace": "homepage",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "password": "AgB4oukzeCml/8qHRS5NRQWcz1qvTGe5i5eqNGupM5eVbCqQyV3AesJhuFCeT1cCM+sjvONHK32x1BkohZvIOzE9D95xh4+NFfD92fEeOrlhvNUfQnaQ7MMZFF6bNv47THZo/5d/kMBAlXaOobc//koww2hPT0OtyyPuflNEltU9jxFX9CPLYSF+feqHoLmYknKQpRFMWhgDsSzkyUTNjzGn7HQkC8+iEdz0zNOTpCcv5tLKB/EgdTIzwlPJeEHmBoVzo77AlvyY1b51HHxufOx5qv4nzKCs5iJbrLDoQRBrZWsq9OSxoGbN0ziNxrDa53rTjlbBrRcRgQZaq5ePkt1uiI40UgSzpmZSbL1JuxSdZtZnsdh4EE/x7RDdWoYCXbI5PUGKjXjvKz4KKP0NiqoBH8XBgk7rhDSi8V3GO9T9GBsgYFlxoS23cnqKHRmuitE4+cX6K4fwW3uWmR172Ksz/Lt2iNplaQmbdEmNunJWDNXyJIScHP7HEeqnEB5iDiQuhm0EQqE+dByW/cF0qFUik1RLbRglVlx5OC0RlWJ5rwpTte5dnzdRlEOWNx7AWWdfIclPKe2xpe6i8FkjAb7mOyQdITkWmi1AFKXr1i4ldzI9CIypqUkLRBMI2cVvTFXfQ2DT15hdHlKk3/kvDTJnXFvXafcu3xcjrtjNidy3rNzKYmeWhdtolCIrRKkiwLqhoEj546YA08ikDnHs",
      "user": "AgBZ/sC/2RxH2Bqa9xo/92Q6QuV1T0mMfZw9TvfpJ8JI7TEHV/oJ4du7ScxEe85nSePIS/mHAUNGnuQxEUsi4SvsC0GDbtBsfJj1c9jeHUJvpscBDyDuIdv1xAcGJFfO7XNup5pipmXDxN1neFbMZklNJSlIBgAo8OlI0mGTg/3xlcTgGedY96nQ/EcMjib1QpkuBIw8AnMKxgqKb2m/yG9k1n/8kmhP6V1jCw3ZigdT+tnB4Dz706evw5viACFdD/MaYRbl6fHS1m2NHNO2AvD0Uvt24StrfRa538s4taxighgjJ1EQgouKgZl+CT69ICyREu1cuDh7gP3nccEDoG11lWlzwe+AqEwgYxjLCMfzgxy6b+RQqMjHlD3Yd6yiQ4fvFZ3Wz3b9Net7m7v1dEBJfXqeJzzNrawhNzbvylGRBLaCPgumdHK8BqGisjDdAj/FgHo8gyOQa6MiNEKOf7hRx+VIU82RN4dlDmMzh2inEotylR+7rkZr0NTqHfIeH63pgjpZ9ug/ATSszZO7IPBvbuATDPUO09feo28P4qPb2GA1pdHCKoDZZAoHxRYoeOei5Gy7OOsbAc7lqBXPeGCfr4vzITS1WEwZNWSDDbn/KIWLAeeodRBrNEd13A+H3ZyOt/K7VOHhbpJUryUVACUv9xtISsOGm1QTZ7luDP/gDixlUHaiQyqaKKsgCUKbaUVeXg6IOL+Al3dLNxJGwdaYb00="
    }
  }
}
