{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "opnsense-api-credentials",
    "namespace": "homepage",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "opnsense-api-credentials",
        "namespace": "homepage",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "key": "AgDVV5iEQNJJAIRR25vV9Qhx1oQK7BvuMWrWmEIORjSboPrNYTDlGG1R0uBlg70GYJ736md09HGtJIMMtLO7QPZ1viCY0QL7BlJ5DqBJu/ZdDfaLMfo7zfTGMqZzgXrlWtYypepcsbPGfSQsxqf5qaxajO1SQaLbFb7C1ltOVm0swbuN0PJOj19j8jVlW9l9aWCYWU07VEO99j16uch6MVAGUwSt2M1YgBI7i+kv+VLLgsT/eT9wKNmpleY+d5FPKjz8ygwnFZoUNFBbbszWg8Ic7W365+aYDHkp9GPrqqe3yONKS+KQuDTJpk8O5EpYn/zq7yhJwMFoervpj2m7bYH8K8x4+e8VvyreZX6G6QsEElVVpEGpA81K3/hgebdvnYDGnpUz7KJvOKbYFJFWFz25Df2HYP1pCcJND273ZcI76+7bsf4ijAQhCxFu+IunFlSW4fYhSE+DM0RStkgTdSLSJczJoeNmZ18+6T467faWRoZvj0dlR7VKdKNbZYbKImHfKJubIV9fSG/yC82wzyVbb+kDcKcP0+Ov9aA36runUuAjUrqM96+FIgX+mnW4EVIfXyTNTLG3Bg4owl7Ok2+WcUrf7S8GoUIutN1auO7neSyzQ9pBilodyiMkjm3z709AeaO7FQurkakZwRVdac46qZxOJ3Tdbnn+AZTsltKsZzh9eDGj8SUXYwA0L25sihuDzzDw9Bfzt/e7MnAHDHQ+8jGSehffaPw8qeQKRndw2KQfUYxfCRhv9X8ekPpNW8V7VFeMGmgOyN2iMIyKYHOrppxxEmDp9FWoJGkWKHqldg==",
      "secret": "AgBrM+GaiYhgZmS7MXeduOLVSdxoLdvADjWwkKqQl7Sl05VI0+9P+5b/m1a2/y6XOMETDvar0N0P9OHxg3UIAGfLnBuNzqx8e8WP/5/IzM3948YpaVamvs6RQ+c/l7/ZfRRDQAYdXdwrlCySzaWIexH/A+UbN+Kh8WV6Ri+49sZ+2u/axe8g1EbEvIYmPBEKueXzCKO00+d7mgT2OCUuCQxCMlCunAwJmwKYj7HcwMMFEI/3WYBW5gJLlJxMr+vs2mcxYh+mPu4qoUGjPQGGXccaXyuXpwugmXlv8nRx8HX0C2oPOjUo6oZanE1m2jQsftvomCMqBJMGAfwmMEkAlFiNk1TjaiP9PqWy0HM4XgqwwqHCypaawi9Rcq0j1MuffwCMeRlF2pN94AGiH4BI3jIO5NAvX6CuUafMlm7IRUw2ZDM0OV2klxZPAJd+0frOn7XwaXKcZcgqRn7Yz79NPRdGxXw2JFP+4/YtfsKuPa4LPeWvbeCPNVWSA1GswKvAQTSx2cJLmSieJE8Mj/pELSLWfMHoSvZjM0y9Cb9auWKr6ItKNHz/fOR0+9cFC50Rtn4Fi9wdyESnj9/vJO3KNRobr6JGKcME1RZTRU3fBvBrU8louLQQADkUerfo7kLd3lR7qJWQMD8EN5trQqVMbAoOJ0ZS9QRH8RBGSp/U2asvrMhx+F+XuguAlAphGWXS1tq2/p1os51DFYZ5oaZ1o2PThLY1A7dhhWNuYFsMrInj9er7UWpQ3Gdi1oSNcczkIP6PtHBTLhNxd0OXUaOQfSu+NeRFUj7D89k0GoNnazjbnQ=="
    }
  }
}
