{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "pbs-api-credentials",
    "namespace": "homepage",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "pbs-api-credentials",
        "namespace": "homepage",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "secret": "AgAsKgztN2tkYc06ZjkGF0u+EKSS2UJm0Opyr+12FC2Sr/GAQVfMIq/5iZL8Q/ZqT2YuCWgrNXapbqd/d+HZA49kmw30Fcb6CyZWkE/Mf/2xdcZ4DI4/F6OJHSItDox4BCh30C6LaMk2V/Yl7eM7XfRhqIimjNeStPx9vZpyqyfvWehzDnhIsUBUvFCDISfoVANxkm3VBOx/DmjI3MUmfHaQvpLfoOtOSiw0CcyS3xfNqZx7SPlX7VMgB+mOCPRpjl8SoKlnDuJUzDgYo+fktzZXyE4nOZryKkEb3TUr1Wx9XyMYwO59+pBhcGarBZaocQ9I71Ez6LDtPPdASwNpUa+Ih3fU6Bzck2081xz76vagjJng/cj8xSrD4ZRtiNHRkiZf/e27Ea85Iv0VOZcW6pl3ZnIj5jU7MXKHkPuZSG5zeJoBuYt6qB2h8k0tl7jBYuLpjQBWkZrLHLD4RYIgdLPZfsf0fPVprLSXDB6p6600zgj2USmNOPZMuHFXhrdzZICMw772150KRDTcVXootyC9mOvbNq0PsCHKuR/4jQt9H9/URNVvIFZGl5DlCWo3VQIIGtQt/3wlVoFY1eHxR9JGL5g1UUUH5hljWehP9p+9VWRB3WMFSBapQh8z4dCn6voY5d7tPJSmaP9imJrZJe4+7Z/v+RYXtLPsV/wC8QDLwfgUgm5g2KqdRsHP0E2ATF2ZLQoUWaiTZcUvXGxGNJZytkb4RJ1oAZ90H3qZul8khCJ9WnA=",
      "token": "AgBzpMI1ZiflubkUnVdj8kDsBuh0BXwv9VmRuP1jum6FSrUnWZMT5BHzSNx57CQgtlJ/pal3gHr0VGH/uSlQ53PWpE41wLotSAeKs9hirMJ5R0JXAopwxYBxbCL/VHMqu3B0bijl9soK5Yn/I3SHEryM9RkHdbIRlbX28lyV2dAJNcTIWT3ZKRsU6bdPLwsbahao7HxkyOHcrvw0ouW0sFk5vN7nylpG6lPdpaEpwVKGea+Obk398CioeBIKGxq+PTRJ6nX6VQIuY7zTuPCk10jVZmw24i7Q4f9clE4J22p/9D1CeCOmAmoDBM32BmEX+hoauyWlbrehtuiM/HMG4KwWQ7Pan+Wa/B08MjHzzjUqh1TmEjLqeem9RUqaR4P8JRAg0AMtUbxt8rXJX4elw/aSx7EaeWjPuflB4vtU/XN0ZZm9CpDW8xA+fCRJsykZnj4pn8fQIQ7LdwfJvjysXDpj//RBcU6pi2yQDjBTB0l6UR5Fzvb4c6HEA6M4kh6ecyBSqKn4XaLlySiSqkZEIACxa9RVaHeAK1gBOjOt9VKTlzUzLyjADrWt45werSfok5uJkZFjq2vQOHrVoSaSMGC2W0hhoFL73oebnnvXsWo5GbMTn3VokmqbsfMOYXTD9/MvBGBYs/4V3mHtbnSTTAh/3NBaJCr2WKbLhAC1TUb4r52VgYDZNg4uP5HI8UrD8ZC1o1Jrs0qFuUQGa5jujlGzu5Skqd0="
    }
  }
}
