{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "proxmox-api-secret",
    "namespace": "homepage",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "proxmox-api-secret",
        "namespace": "homepage",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "secret": "AgCQdr9z/v8bp0E0W03vwegcdFEDEZaew1cLmsJqfx8ZP3PajatipOrGPMIZzi8sVPk5IMXYJCytw6pbjcnVOKpCZJJXOdTShT8sUY7xEVL2TWudYEnkD4uzKaLFrhot0vVLxlqYOQIfvKqd4mhsJ+oYtLwZSUzZ+P0yb2PTMB8CiJXkMVryLzfl5xxacCRx556R1YSjtpftFhgCGFgvi7AhjkPCndg2ZZacktv/6lderez5cDL9MyC1FWg9MjupRUfGxZZBGMI6S7v1i/QWGp/pxcjyhqdNq0fSJzwKp+5RpK3NYEamNOG61w22YtEFrVa9k1uBqWz7nQlSkEtmgG+jNxD5Rl/Qece6F2Zi5YGNGNr1p6hqy/6LCkPvd8V8ctGzO6GXWABMFGPT3KVaF7eKx7qaybrgUEwuxTIOoZ+3I58aZ8V5jyudai0XNf1UmQRwAZX+Z4muAv8k1uOi10kO+iBkFZzpcLVTIPEzbih+3ahpz3DTv5y5EANqiEBLh3cYFVKD9ST2AgAF2+zMJJoVYMc4My7MO6BLoerevM8eQ7cLVCK8NXDWHZ8H9sr0mbfR+J+A0ElAZBvupRUiPP9ieIUoLCxt+7KjMlTSbnkexoSpKM45YCmq57BfWffskMzIL2ulu4fg4heEkoBhD/bcwRlNE0hxGSSGfTN5YuGPX7eLiVbfhYb/0TgAcS7oa+8dPH+WV20FynSO1G2NON8J6xfBPb0+fXKeFM6Fi0OiCKtpRuQ=",
      "token": "AgCsHKot62xeNwoioxkmSS6vwhQglDaCgZ5KcwOklXLw+od2X9nS2h/+HxdG7f1xq51JYyQN3o+khUUIy1s2eBqbGnAmN5bw60yE172K9tc802AxYkTf2o5Ydu5FcJTVWOXEYUIR+k18xUHdn/IhG7NsGP33+oQqv7qnnWrx562D2diiHV+H2jTEgHif5n+XjhxyXuSd+cPnfRmRUa5yspoRfznxNyoUYXFZOX57RwjPWVQRg0LOjSCwDKnKbsp6N27hkzSch6sahPvqMBk50q2KrkPf315NIQ8+79+b20YckLhXafhS2frz+C7w0lIT/e7N7pvwwxzV78oVEMGzS3Jv3VPK/tH1vRDBVN2C1Hf3hpoaY7dkxpe7CrPRhIWOV2w6q9NPLFiZc4817YtbI2U3T73ZYt+SIsYn5RYLuDEsYrWLBbFmoyEde3HM7fhJUyruh1et6/pRb0I3a2TTfHlippBXbzsKl+fGebfTdv07Cc/EXXkZnI9pn1erREUJInF4kP/OMEZh5/PWZkA8W4iMoJC4gsInZw/K+eTsgw7WJJ0UeMzq3xLbXrn1yS/1t017sg1RheG+kZ4vx65BdccLNYq7UeeVRz8CRQQgHYhU7+jyaVdUC5dZ9NU9fzRLikMheWKbPAtP53LxbCUWSoBey/3mwWHUmMcjIRuI04ZuqTdekNLZQjzjnc82iUsksK2zJndU4a/ZQevbX3jXY20wnl0U8c0="
    }
  }
}
