{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "pgadmin-password",
    "namespace": "pgadmin",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "pgadmin-password",
        "namespace": "pgadmin",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "pgadmin-password": "AgDdPQZam/cEkAx+QNQbPH5GFohXGF2hXDunFzU10Qj60+67JgzV2u3KXoVtDVr8lEk0rFJj0R/MHmcriM7+SXXQkEYB9HC9FtlJ3S0RqIVKhga+stmOZgNM0I4vrLDLe42JeX0Y8E1GXylx9Wc0lQG0m768+krorlHumy4r3R1aax5eB99/SSXjl0f8v2Pys2YhBU4TliLdK8t4/EmdDsZmvIglz41S/s6/t88OteSwPgzxDeK1L/eY5hwfkDpFdPJxNcsp4yfc7Kru0KR8hOo0eYAoWIobJaWOyDFLOXaueEuMmR1mwlErL9+nXqoa94a05DcM00iFZBsU6VKlngIkgEhyTT/dMiTXMa9QovYxC9FoTLYV+7z/NkJUj5Jo7YkUiwVN1eYh9/FUXoHtnI7S4NGSGTFD/dEHgIzqQPhhfAbU45CLfIcHAcnr72YMEnGkQtCs4ZntRhLLxhtYep8vmoZFywBssI+lacTfn/P01TTnhFYu1WVrdBcjBRyaD3/nD7DiJbWa5erb6ceS0r27Px+OuOXYOdd6eIzw2wayP1XqZgVGPKrKREK/IfHz8TvGkOq2QwEODMqlFepATOqHZd1ojlTbCky4CkfqULHdtWBMNUJM+v87RrULcsZqADJ9N5cVFsbcgTDKX6vfLhF71Jcq2ztkEsnHtnaY4xT3AX9ZXlCDhJBqXKW/mfChno+KoaFlwfRbxymWInQxIFY="
    }
  }
}
