apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Project for Demo Apps

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/Gu35t09/TalosCluster.git
      revision: HEAD
      directories:
      - path: argocd/demo/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "demo"
      source:
        repoURL: https://github.com/Gu35t09/TalosCluster.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
