---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-certificates-greyroom-net-production
  namespace: letsencrypt-production
spec:
  secretName: test-certificates-greyroom-net-production
  issuerRef:
    name: issuer-letsencrypt-production
    kind: ClusterIssuer
  commonName: "test.greyroom.net"
  dnsNames:
    - "test.greyroom.net"
