{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "garage-s3-velero-bucket-credentials",
    "namespace": "velero",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "garage-s3-velero-bucket-credentials",
        "namespace": "velero",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "credentials": "AgDCNK7cax0ZfjFK8yLDcPiMZ9T7mi4tMvxYfen44aXgZZeMN2yJyHmSexUfqFq3DIgvXhrTBAJj0Ha/OLKo/eAySY1hPsm9CnyCaQFFNLF+1coVaLlTdJhgz/1KKppCFrzK1J4xOTSWj1roT1jGq5J1V5jckKqJvJ9CVCloISIYRM86lcsDx7ZMhlocI4EPbzYKyfoswQp2E1UqA7k4nH55GFL2K2QQiNmq9gZf02q1y991KLLoFr1LaNsZxkwJMDbPLxlBanLbtTOEnLWiCXAXcOvVZw/+eu2yJcQcjVH83r+OnfWgTxhxym2v7wwKcgnp+jXxosAh7iguB+GZK1UfJd6gI7EtcjgcLk/2bhqAeT+4r+LmZhCSJPpLFsdwbVgMKRoZv/Txoou5nAzi1vM+W70ZtPmnoQOviMC7so4A/B6cYY1B+Q5E8gTpVSh+1mN2BVKLwqJnvKPTLuubNWZAGTiLfzgp/H2L2X6AAdHdEm5lOJAAqvHfK2cdP4nR3D6TnnZhsc4yFWYkCVZs/W5LFdHIvWHvzvxcAIHAWaehlU+/qoeQqumJb5EstrPy3CeLeaaYzJIBCLG5oQJo9/Tf+gFL4K8yps3J9DLoghFcXj4riiWvamqEkdoRKNaq3DUU/2CGy1sxtuc/ZhaIxFI/NlcGCEOURdoRCy3ihSajs/9NwFdR+2eugYyyhjcIwAc76VxNdASK4XUU+c9EElpgJaYhdPq9DZmpuH8Y61poMAVybqXTq5/4tq5fdDm5/58Xy0VwRBOlCvQ0EWv6I17DICo3HS8zjbwPX6VLMKWpz21W940lGKEMOFCz8R7mkgiN4F+nCelhJ3lp5CLGEsAf4e5n1Q4zLRP2eBisvhg5jKXusMQ="
    }
  }
}
