{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "garage-s3-velero-bucket-credentials",
    "namespace": "velero",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "garage-s3-velero-bucket-credentials",
        "namespace": "velero",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "credentials": "AgDgB7BjfNhV0vYdSId8O7FQaZP8JJU/lQAnBwRqdmwPH6FHIXk8jP/7UqDmr+G3LM6Ehcl1C1E4UDa9wI/S5JzWgV3+/vbdcC9gnR0Ymq2GzvPbJ+hQ+/pHgtuZcj8olcZy76BanKM2lbVnNsS2+uFCD8rcnHIBHsyyu4hqHTyIKjxC9zB0Ho41ggTEobLK8xEFimWhX5c5nHtdmVTdmFKbFybQQ//Yigq0tzc9qe/HvS1MPePuSB3oa+RC8pvqIXptlDJxgbvTGCPomRz5q9SWapOlia8gqGlMrWXaDvxkzQrixR4/Mf1QR6+p+4mI0nUZrMD4Yv4yiKU0flzMFys7RTWuNHsiKO9vPl8Q60wS+tSBtU0j9H+EqQR/rfm7KJETpWl31GsVdPjcRja7uQBjk1DJGUVIpBydHkL1QpMCNu/xVC4QfCPL3K/B92672QftYAencIZGZCemE7WUX9PCtJ/ROFul27qhqFGfSbKjjkwQpIKsIjtJ9X5s425m8yOHimtxfB9y6d11dcH1gUYJ2pLU2JgPOO8zGOos+9tClphASLBVHfL6D6oWbNf/h2ZmS6QhNZo34kqLoHCoxBPteKb9SWl2b4RyGd+0xtIQ8sD6HJwzIQl8ZvOTB8GwmG8mnHFtAOl63/AP2E/yvHvYnRijTnXUGT6hTTEgHe8OPPxVAt0taSEWU8sBm47L+u4cKygfMYijwP/ShGF17tLQa5PC4gVrhTCJKHqwOkIbYf+hl5bcHPpyySD0hytDB1alZ4S+H37I72v0yRLRFRYAL7MOdCh0DC9tzRjbSZWwyDKK9PadjSGBAA7+6j26fPHgxN3DiFHb/X7yi2/+o8c1iNfx45CHes7xH5jJStSQiL2v2Fo6qt43tA0Wnkov9mDcCxUTuPmvrf2QRib46/cs9f7zBsQoWY2Mhq+sOA1Totd7S03sv2KqmoZot4H4vYICh7wGp6Kfla8p8c/Ov2UfNvbjVGp6KW6vakkvP+tM6LMyRRD9EPc/c7Tl10pq0N2Y+cu3RePXCm6W5Vs9"
    }
  }
}
